id: audit_files_owner_configure
title: "Configure Audit Log Files to be Owned by Root" 
discussion: |
  Audit log files _MUST_ be owned by root.
  
  The audit service _MUST_ be configured to create log files with the correct ownership to prevent normal users from reading audit logs.
  
  Audit logs contain sensitive data about the system and users. If log files are set to only be readable and writable by system administrators, the risk is mitigated.
check: |
  /bin/ls -n $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}') | /usr/bin/awk '{s+=$3} END {print s}'  
result:
  integer: 0
fix: |
  [source,bash]
  ----
  /usr/sbin/chown -R root $(/usr/bin/grep '^dir' /etc/security/audit_control | /usr/bin/awk -F: '{print $2}')
  ----
references:
  cce:
    - CCE-84710-3
  cci:
    - CCI-000162
  800-53r4:
    - AU-9
  srg:
    - SRG-OS-000057-GPOS-00027
  disa_stig:
    - AOSX-15-001012
  800-171r2:
    - 3.3.8
macOS:
  - "10.15"
tags:
  - 800-171
  - cnssi-1253
  - 800-53r4_low
  - 800-53r4_moderate
  - 800-53r4_high
  - STIG
mobileconfig: false
mobileconfig_info: